name: jsonbug
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  json_annotation: ^4.4.0

dev_dependencies:
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
